spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/board
    username: root
    password: '1234'
    driver-class-name: org.mariadb.jdbc.Driver
  web:
    resources:
      static-locations: 'classpath:'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
logging:
  level:
    org:
      springframework:
        security: DEBUG